# src/ui/cpp_template.py

# This is the default C++ code that will be placed in a new project.
DEFAULT_PROJECT_TEMPLATE = """/**
 * @file project.cpp
 * @brief Main project file for a new scene.
 * @note This file was automatically generated by the editor.
 */

// Include necessary headers from the core engine
// For example: #include "systems/render/engine/renderer.hpp"
// For example: #include "systems/render/material/implementations/phongmaterial.hpp"


/**
 * @class MyProject
 * @brief A class to define the scene, objects, and animations.
 */
class MyProject {
public:
    /**
     * @brief Constructor where you set up the scene.
     */
    MyProject() {
        // TODO: Add objects to the scene
        // TODO: Define materials
        // TODO: Link materials to objects
    }

    /**
     * @brief Called every frame to update animations and logic.
     * @param time_delta The time elapsed since the last frame.
     */
    void update(float time_delta) {
        // TODO: Add per-frame update logic here
    }

    /**
     * @brief (Optional) A function to get a specific object for rendering.
     */
    // Object3D* get_render_object() {
    //     return &my_main_object;
    // }

private:
    // --- Declare your scene objects and materials here ---
    // Example:
    // PhongMaterial my_shiny_material;
    // Sphere my_sphere;
};
"""
